SET SCHEMA FN71970;

CREATE TABLE USERS
(
    USERNAME VARCHAR(25) NOT NULL PRIMARY KEY,
    UPASSWORD VARCHAR(20) NOT NULL,
    FAVGENRE VARCHAR(10),
    MTAX INTEGER NOT NULL
);

CREATE TABLE ARTISTS
(
    USERNAME VARCHAR(25) NOT NULL PRIMARY KEY,
    APASSWORD VARCHAR(20) NOT NULL,
    SONGS INTEGER NOT NULL,
    ALBUMS INTEGER,
    YTAX INTEGER NOT NULL,
    MSTREAMS INTEGER,
    INCOME DECIMAL(16, 2)
);

--DROP TABLE ARTISTS;

CREATE TABLE PLAYLISTS
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME VARCHAR(20) NOT NULL,
    UNAME VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (UNAME) REFERENCES USERS(USERNAME)
);

CREATE TABLE SONGS
(
    NAME VARCHAR(20) NOT NULL,
    SYEAR INTEGER NOT NULL,
    ANAME VARCHAR(25) NOT NULL,
    ALBUM CHAR(1),
    GENRE VARCHAR(10),
    PRIMARY KEY (NAME, SYEAR),
    FOREIGN KEY (ANAME) REFERENCES ARTISTS(USERNAME)
);

CREATE TABLE CONTAINS
(
    PID INTEGER NOT NULL REFERENCES PLAYLISTS(ID),
    ANAME VARCHAR(25) NOT NULL REFERENCES ARTISTS(USERNAME),
    SNAME VARCHAR(20) NOT NULL,
    SYEAR INTEGER NOT NULL,
    PRIMARY KEY (PID, ANAME, SNAME, SYEAR),
    CONSTRAINT my_foreign FOREIGN KEY (SNAME, SYEAR)
                    REFERENCES SONGS(NAME, SYEAR)
);

ALTER TABLE USERS
ADD CONSTRAINT CK_USER_MTAX CHECK(MTAX = 7);

ALTER TABLE ARTISTS
ADD CONSTRAINT CK_ARTIST_YTAX CHECK(YTAX = 60);

ALTER TABLE SONGS
ADD CONSTRAINT CK_SONGS CHECK(ALBUM IN ('Y', 'N'));