SET SCHEMA FN71970@

--скрипт, в който са дефинирани тригери и тестове с тях (поне два тригера, 
--като поне един от тригерите трябва да извиква процедура);


CREATE TRIGGER UPD_STREAMS_TRIG1
AFTER UPDATE OF MSTREAMS ON ARTISTS
REFERENCING OLD AS O NEW AS N
FOR EACH ROW
 UPDATE ARTISTS
   	SET INCOME = O.MSTRAMS*0.44
   	WHERE USERNAME = O.USERNAME@
 
 SELECT USERNAME, MSTREAMS, INCOME
 FROM ARTISTS@

 UPDATE ARTISTS
 SET MSTREAMS = MSTREAMS + 100
 WHERE USERNAME = 'Queen'@
 
CREATE TRIGGER DEL_SONG
BEFORE DELETE ON SONGS
REFERENCING OLD AS O
FOR EACH ROW
WHEN(O.ALBUM = 'N')
DELETE FROM SONGS
WHERE NAME = O.NAME AND SYEAR = O.SYEAR@

CREATE OR REPLACE TRIGGER UPD_ARTIST_T 
AFTER UPDATE ON ARTISTS
REFERENCING NEW AS N
FOR EACH ROW
BEGIN ATOMIC
   DECLARE SC INTEGER DEFAULT 0;
   CALL FN71970.SONGS_CHECK(N.USERNAME);
   GET DIAGNOSTICS SC = RETURN_STATUS;
   VALUES(CASE WHEN SC < 0 THEN CAST(RAISE_ERROR('70001', 'NO SONGS FROM THIS ARTIST') AS VARCHAR(70))END);
END@

 UPDATE ARTISTS
 SET SONGS = 0
 WHERE USERNAME = 'Queen'@