SET SCHEMA FN71970;

CREATE VIEW INFO
    AS
      SELECT A.USERNAME AS ARTIST, S.NAME AS SONG, S.SYEAR
        FROM ARTISTS A, SONGS S
        WHERE S.ANAME = A.USERNAME;

CREATE VIEW PLAYLISTINFO2
    AS
      SELECT P.NAME, PC.SNAME, PC.ANAME
        FROM CONTAINS PC, PLAYLISTS P
        WHERE PC.PID = P.ID;
        
SELECT * FROM PLAYLISTINFO2;
SELECT * FROM INFO;