 SET SCHEMA FN71970@
 
 --процедура с курсор и входни и изходни параметри; +
--процедура с прихващане на изключение; +
--процедура с курсор и while цикъл; +

CREATE OR REPLACE PROCEDURE CHECK_TAX(IN V_USERNAME VARCHAR(32), OUT V_SQLSTATE CHAR(5), OUT V_SQLCODE INTEGER)
BEGIN
   DECLARE CNT_R ANCHOR ROW FN71970.USERS;
   DECLARE SQLCODE INT DEFAULT 0;
   DECLARE SQLSTATE CHAR(5) DEFAULT '00000';
   DECLARE R INTEGER;
   DECLARE CNT INT DEFAULT 0;
   DECLARE AT_END INT DEFAULT 0;
   
   DECLARE M_TAX INTEGER;
   
   DECLARE NOT_FOUND CONDITION FOR SQLSTATE '02000';
   DECLARE NO_TAX CONDITION FOR '42424';
   
   DECLARE C1 CURSOR FOR SELECT * FROM FN71970.USERS
                          WHERE USERNAME = V_USERNAME;
   							
  -- DECLARE EXIT HANDLER FOR NO_TAX
	--CALL DBMS_OUTPUT.PUT_LINE('The user has no monthly tax!');
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	SELECT SQLCODE, SQLSTATE INTO
	V_SQLCODE, V_SQLSTATE
	FROM 
	SYSIBM.SYSDUMMY1;
   
DECLARE CONTINUE HANDLER FOR NOT_FOUND
   SET AT_END = 1;
     
SET M_TAX =(SELECT MTAX FROM FN71970.USERS WHERE USERNAME = V_USERNAME);
     
IF M_TAX = 0 THEN 
SET R = RAISE_ERROR('700001', 'The user has no monthly tax!');
END IF;
  
 OPEN C1; 
  SET CNT = 0;
  FETCH C1 INTO CNT_R;
     
     WHILE AT_END = 0 DO
      SET CNT = CNT + 1;
      FETCH C1 INTO CNT_R;
     END WHILE;
 CLOSE c1; 
END@

CALL CHECK_TAX('kaloqm', ?, ?)@
UPDATE USERS 
SET MTAX = 0
WHERE USERNAME = 'kaloqm'@

CREATE OR REPLACE PROCEDURE FN71970.P_STREAMS (IN V_USERNAME ANCHOR ARTISTS.USERNAME)
DYNAMIC RESULT SETS 1
BEGIN
    DECLARE C CURSOR WITH RETURN FOR
        SELECT MSTREAMS FROM FN71970.ARTISTS WHERE USERNAME = V_USERNAME;
    OPEN C;
END@

CREATE OR REPLACE PROCEDURE FN71970.CHECK_ALBUM (IN V_SONG VARCHAR(32), IN V_YEAR INT)
DYNAMIC RESULT SETS 1
BEGIN
    DECLARE C CURSOR WITH RETURN FOR
        SELECT ALBUM FROM FN71970.SONGS WHERE NAME = V_SONG AND SYEAR = V_YEAR;
    OPEN C;
END@


CREATE OR REPLACE PROCEDURE SONGS_CHECK(IN ARTIST ANCHOR ARTISTS.USERNAME)
LANGUAGE SQL 
DYNAMIC RESULT SETS 0
MODIFIES SQL DATA
BEGIN
  DECLARE SC INT DEFAULT 0;
  SET SC = (SELECT SONGS FROM ARTISTS WHERE USERNAME = ARTIST);
  IF (SC > 0) THEN
      RETURN 0;
  ELSE
      RETURN -200;
  END IF;
END@

CALL FN71970.P_STREAMS('Queen')@
CALL CHECK_ALBUM('This is me','2008')@