SET SCHEMA FN71970@

--скрипт, в който са дефинирани функции и тестове с тях (поне две функции);

CREATE OR REPLACE FUNCTION IN_PLAYLIST(IN V_PNAME VARCHAR(32))
RETURNS INT
RETURN
    SELECT COUNT(*)
    FROM CONTAINS C, PLAYLISTS P
    WHERE P.ID = C.PID
    AND P.NAME = V_PNAME@

SELECT * FROM CONTAINS@
VALUES FN71970.IN_PLAYLIST('MEMES')@

CREATE OR REPLACE FUNCTION SONGS_ARTISTS()
RETURNS TABLE
    (
    SONG VARCHAR(32),
    ARTISTS VARCHAR(32)
    )
RETURN
    SELECT S.NAME, A.USERNAME
    FROM SONGS S, ARTISTS A
    WHERE S.ANAME = A.USERNAME@

SELECT RESULT.SONG AS SONG, RESULT.ARTISTS AS ARTIST
FROM TABLE(FN71970.SONGS_ARTISTS()) AS RESULT@